spring.datasource.url=jdbc:postgresql://localhost:5432/YourFirstPersonalAssistantBot
spring.datasource.username=admforbot
spring.datasource.password=123321
telegram.bot.token=8028993738:AAEDYkFkthZDPJoVWL9OfHy1w8TNPuuxv-c

spring.liquibase.change-log=classpath:liquibase/db.changelog.yml